### ISSUE TITLE
Debian 12 build issue

### ISSUE THREAD

**Issue by pnwpoe** [micahflee/qube-apps#10]
After cloning the repo and installing dependencies in an app qube, the build fails...

$ ./build_deb.sh 
running bdist_deb
running sdist_dsc
running egg_info
writing qube_apps.egg-info/PKG-INFO
writing dependency_links to qube_apps.egg-info/dependency_links.txt
writing top-level names to qube_apps.egg-info/top_level.txt
reading manifest file 'qube_apps.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'qube_apps.egg-info/SOURCES.txt'
Traceback (most recent call last):
  File "/home/user/qube-apps/setup.py", line 13, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
    super().run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/stdeb/command/bdist_deb.py", line 34, in run
    self.run_command('sdist_dsc')
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
    super().run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/stdeb/command/sdist_dsc.py", line 30, in run
    debinfo = self.get_debinfo()
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/stdeb/command/common.py", line 197, in get_debinfo
    debinfo = DebianInfo(
              ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/stdeb/util.py", line 934, in __init__
    for line in long_description.split('\n'):
                ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

Qube Apps failed to build!

**Comment by x45dev** [comment]
Bump. Same deal. 
I think this relates the `stdeb` library, which seems to no longer be maintained. Discussion covers it in this issue: https://github.com/freedomofpress/dangerzone/issues/773

**Comment by sysfu** [comment]
> Bump. Same deal. I think this relates the `stdeb` library, which seems to no longer be maintained. Discussion covers it in this issue: [freedomofpress/dangerzone#773](https://github.com/freedomofpress/dangerzone/issues/773)

That ticket you linked has been closed, apparently as won't fix?

I took a look at the [stdeb](https://github.com/stdeb/stdeb) project and there user nuclearsandwich has been a few dozen commits to it this year, so apparently it's not dead?
